<?php

/**
 * Implements hook_install().
 */
function node_menu_item_visibility_default_behaviour_install() {
	// Set the weight to 1
	db_update('system')
		->fields(array('weight' => 1))
		->condition('type', 'module')
		->condition('name', 'node_menu_item_visibility_default_behaviour')
		->execute();
}

/**
 * Implements hook_uninstall().
 */
function node_menu_item_visibility_default_behaviour_uninstall() {
	$node_types = node_type_get_names();
	
	foreach ($node_types as $type => $name) {
	  variable_del('default_node_menu_item_visibility_default_behaviour_show_hide_' . $type);
	}
}

